export const themes = {
  dinosaurs: {
    name: "🦕 Dinosaurs",
    background: "#f7f2eb",
    card: "#fcf9f5",
    primary: "#1e1916",
    secondary: "#4a423b",
    muted: "#8a7e74",
    accent: "#b28b6a",
    accentLight: "#dcc8b4",
    font: "serif",
  },
  football: {
    name: "⚽ Football",
    background: "#f0f7f0",
    card: "#fafffa",
    primary: "#1a2e1a",
    secondary: "#3a5a3a",
    muted: "#7a9a7a",
    accent: "#2e7d32",
    accentLight: "#c8e6c9",
    font: "sans-serif",
  },
  space: {
    name: "🚀 Space",
    background: "#0a0e1a",
    card: "#141c2a",
    primary: "#e8edf5",
    secondary: "#a8b8d0",
    muted: "#6a7a90",
    accent: "#4a7af7",
    accentLight: "#8aafff",
    font: "sans-serif",
  },
  fantasy: {
    name: "🧙 Fantasy",
    background: "#1a0e1a",
    card: "#2a1a2a",
    primary: "#f5e8f5",
    secondary: "#c8a8c8",
    muted: "#8a6a8a",
    accent: "#9b59b6",
    accentLight: "#d4a0d4",
    font: "serif",
  },
};